spring:
  profiles:
    active: dev
---
server:
  port: 12345
spring:
  profiles: dev #开发环境
  application:
    name: spring-cloud-config-demo-dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka7000.com:7000/eureka

---
server:
  port: 67890
spring:
  profiles: test #测试环境
  application:
    name: spring-cloud-config-demo-test
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka